title: Props
description: >-
  Multi-layered properties and secrets management library, for JAVA.
markdown: kramdown
kramdown:
  parse_block_html: true
theme: jekyll-theme-leap-day
show_downloads: true
google_analytics: UA-1713578-17
exclude:
  - Makefile
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
github:
  repository_url: "https://github.com/MihaiBojin/props"
  zip_url: "https://github.com/MihaiBojin/props/archive/v0.0.4.zip"
  tar_url: "https://github.com/MihaiBojin/props/archive/v0.0.4.tar.gz"
  is_project_page: true
  owner_url: "https://www.linkedin.com/in/Mihai-Bojin"
  owner_name: "Mihai Bojin"
