on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    name: Continuous Integration Tests
    runs-on: adoptopenjdk:11.0.9.1_1-jdk-hotspot
    steps:
      - uses: actions/checkout@v2

      - name: Installing dependencies
        run: make setup

      - name: Activating JDK env
        run: |
          . ~/.sdkman/bin/sdkman-init.sh
          sdk env

      - name: Check code formatting
        run: |
          make fmtcheck

      - name: Run static analysis
        run: |
          make vet

      - name: Run tests
        run: |
          make test
